### ISSUE TITLE
Ability to use "custom variables" as "Action Command ID" in "reaper custom action"

### ISSUE THREAD

**Issue by gonokokkus** [bitfocus/companion-module-cockos-reaper#13]
Hi,
is there are way to use a custom variable as a value in "Action Command ID" in a reaper custom action?
The idea is to increase or decrease the value of the custom variable by using a plus or minus button on the stream deck.
The current value of the variable then needs to be the value of a reaper custom action. 

I have tried to implement it, but the reaper custom action button ignores the value of the variable.

Thank you for your help...

**Comment by LykaiosNZ** [comment]
This will be fixed in the next version 🎉

**Comment by gonokokkus** [comment]
> This will be fixed in the next version 🎉

Perfect. Thank you.
Thank you for your support and the information. As soon as the new version is available, I will test it.
