### ISSUE TITLE
reaper: Change colors based on a custom OSC message not working as intended

### ISSUE THREAD

**Issue by benwingrove** [bitfocus/companion-module-cockos-reaper#14]
I have tried using the "reaper: Change colors based on a custom OSC message" feedback but no matter how I try formatting the message, message type and value I am getting no results. I have used several OSC Listeners and they are seeing the correct output from reaper, in this case "/track/1/solo) FLOAT(1)"

**Comment by super-frais** [comment]
Not working here either - here's how I got around it for the time being:

1) Created a custom variable on the button's $Variable tab to store the state of the Reaper target (in my case whether an FX is bypassed)
2) Companion can change its own custom variables via OSC  (port 12321 by default) - from the docs:

>       /custom-variable/<name>/value <value>
>       Change custom variable value

...so I set a command in the Reaper OSC pattern file like so: 

      `FX_BYPASS b/custom-variable/bypass/value`

This updates my custom variable with the state of the FX bypass state.

3) Then - and this is the special sauce - I went into the Feedback tab for the button, and have it update the color based on the value of the custom variable (see attached picture). It's a little hack-y, but it does work.

![feedback_tab](https://github.com/bitfocus/companion-module-cockos-reaper/assets/48494213/2b9eb5d4-f0a8-4b94-873f-72a4a7680f19)

**Comment by LykaiosNZ** [comment]
From my testing it does work but I had to restart after adding the feedback as it only sets up handlers during initialization, give that a go.

**Comment by super-frais** [comment]
Yeah the standard feedback method definitely doesn't work here. This is after restarts, updating Companion version, etc. The above is the only way I am able to get it to work.

**Comment by LykaiosNZ** [comment]
I added this feedback to a button and restarted Companion and the button correctly changes colour when I toggle repeat on/off. I am using the default pattern.

![image](https://github.com/bitfocus/companion-module-cockos-reaper/assets/19542938/f15e3b73-9ebd-4e0a-b104-0f49d98749a1)

I am working on migrating the module to support Companion 3.x and will fix feedbacks not being refreshed until restart as part of that.
