### ISSUE TITLE
Support Companion 3.x

### ISSUE THREAD

**Issue by LykaiosNZ** [bitfocus/companion-module-cockos-reaper#15]
I've taken it upon myself to get this module migrated for Companion 3.x and will track my progress here.

- [x] Create 3.x module manifest
- [x] Convert to TypeScript
- [x] Configuration
- [x] Refactor actions
- [x] Refactor variables
- [x] Refactor feedbacks
  - [x] Fix #14
- [x] Refactor presets
- [x] Refactor upgrade scripts
- [x] Implement #13

As part of this work I have ripped out the OSC message handling implemented in the module and replaced it with [reaper-osc](https://github.com/LykaiosNZ/reaper-osc.js/). It already has better coverage of Reaper's OSC controls (e.g. it supports volume/pan which would be useful for implementing #12). Hopefully this makes the module more maintainable.

Working branch is available here: https://github.com/LykaiosNZ/companion-module-cockos-reaper/tree/support-3.x

**Comment by LykaiosNZ** [comment]
@odedd @monoxane you two are the listed maintainers for this module, would you have any objections to me being added and/or would you like removing from the list?

**Comment by mstberto** [comment]
Any updates here @LykaiosNZ? cc: @odedd and @monoxane

**Comment by mstberto** [comment]
@LykaiosNZ what does it take to get this into the larger Companion updates? I've noticed there have been a few releases but no update for this.

**Comment by istnv** [comment]
@LykaiosNZ Is this ready to include in Companion? 
When you have an update ready, post a message in #module-development on  Slack.
https://join.slack.com/t/bitfocusio/shared_invite/zt-1v8877kva-XnhKMI3maDyJ2vruqrp2Dw
