### ISSUE TITLE
Build errors

### ISSUE THREAD

**Issue by istnv** [bitfocus/companion-module-cockos-reaper#21]
The `main:` parameter in `package.json` needs to list the module base/entry point.
Leave the `version:` parameter in `manifest.json` at `0.0.0`, the build process will update it to match the version in `package.json`

You can test build with `yarn compaion-module-build` in your repo. It will create a package similar to the companion builds.

**Comment by LykaiosNZ** [comment]
Should be fixed by https://github.com/bitfocus/companion-module-cockos-reaper/commit/4d705961f977c36bd4c0626c3f8301b833013de6
