### ISSUE TITLE
"Change colors based on a custom OSC message" not working?

### ISSUE THREAD

**Issue by cjunekim** [bitfocus/companion-module-cockos-reaper#6]
Hello

There is "Change colors based on a custom OSC message" feedback option in this module. However, it doesn't seem to work.

For example, track mute. Reaper will send,

/track/1/mute with float(32 bit, big-endian) 1.0 when the track 1 is muted. I have set,

Message : /track/1/mute
Message Type : Number
Value : 1.0

This module doesn't react to this feedback message.

**Comment by cjunekim** [comment]
I experimented some more and found that the Value has got to be "1" instead of "1.0".

However, the internal status isn't updated, which means the internal status and the reaper button status can be out of sync and you have to press the stream deck button twice to make it toggle.

**Comment by cldswm** [comment]
any updates on this? or have it been properly implimented?

**Comment by super-frais** [comment]
@cldswm Still not working it seems - I posted a workaround here:

https://github.com/bitfocus/companion-module-cockos-reaper/issues/14
